AllCops:
  TargetRubyVersion: 2.6
  Exclude:
  - lib/seeds/reviews/*
  - tmp/**/*
Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
  - http
  - https
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Rails:
  Enabled: true