class Review < ApplicationRecord
  self.table_name = :reviews
  self.sequence_name = :autogenerated

  belongs_to :movie
  belongs_to :bro

  after_save :touch_movie

  def touch_movie
    movie.touch
  end
end